app_blog/app_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
]

app_blog/blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('',views.index, name='index'),
    path('detail/<int:blog_id>/', views.detail, name='detail'),
    path('new/',views.new, name='new'),
    path('delete/<int:blog_id>/', views.delete, name='delete'),
    path('edit/<int:blog_id>/', views.edit, name='edit'),

]

app_blog/blogs/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(blank=False, null = False, max_length=150)
    text = models.TextField(blank=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    updated_datetime = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

app_blog/blogs/forms.py
from django.forms import ModelForm
from django.forms.models import model_to_dict 
from .models import Blog

class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'text']

app_blog/blogs/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Blog
from .forms import BlogForm
from django.views.decorators.http import require_POST
# Create your views here.

def index(request):
    blogs = Blog.objects.order_by('-created_datetime')
    print(blogs)
    return render(request, 'blogs/index.html', {'blogs': blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    return render(request, 'blogs/detail.html',{'blog' : blog})

def new (request):
    if request.method == "POST":
        form = BlogForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')
    else:
        form = BlogForm
    return render(request, 'blogs/new.html', {'form' : form})

@require_POST
def delete(request, blog_id):
    blog = get_object_or_404(Blog,id=blog_id)
    blog.delete()
    return redirect('blogs:index')
    
def edit(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    if request.method == "POST":
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            form.save()
            print("success update")
            print(form)
            return redirect( 'blogs:detail', blog_id=blog_id)
    else: 
        form = BlogForm(instance=blog)
    return render(request, 'blogs/edit.html', {'form' : form, 'blog': blog})

    

app_blog/blogs/templates/blogs/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
</head>

<body>
    <h1 style="text-align: center;"> {{ blog.title }}</h1>
    <div style="width: 70%; margin: 0px auto;">
        <div style="margin: 60px 20px;">
            {{blog.text}}
        </div>
        <div style="text-align: center; margin-top: 50px;">
            <a href="{% url 'blogs:edit' blog.id %}">
                <button class="btn">Edit</button>
            </a>
            <form method="POST" action="{% url 'blogs:delete' blog.id %}">{% csrf_token %}
                <button class="btn" type="submit" onclick='return confirm("Do you delete this?");'>Delete</button>
            </form>
        </div>
        <div style="text-align: center; margin-top: 50px;">
            <a href="{% url 'blogs:index' %}">Return Top</a>
        </div>
    </div>
</body>

</html>

app_blog/blogs/templates/blogs/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit</title>
</head>
<body>
    <h1 style="text-align: center;">Edit Article</h1>
   <div style="width: 70%; margin: 0px auto;">
    <div>
        <div style="margin: 60px 20px;">
            <form action="{% url 'blogs:edit' blog.id %}" method="POST">{% csrf_token %}
                {{ form.as_p}}
                <button class="btn" type="submit">Save</button>
            </form>
        </div>
        <div style="text-align: center; margin-top: 50px;">
            <a href="{% url 'blogs:detail' blog.id %}">Return Detail</a>
        </div>
    </div>
   </div> 
</body>
</html>

app_blog/blogs/templates/blogs/index.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Blog</title>
    </head>

    <body>
        <h1 style="text-align: center;">My Blog</h1>
        <div style="width: 70%; margin: 0px auto;">
                <a href="{% url 'blogs:new' %}">Add Article</a>
            <br>
            {% for blog in blogs %}
            <div>
                <h3>{{ blog.title }}</h3>
                <div>{{ blog.text | truncatechars:100 }}</div>
                <div style="text-align: right;">
                    <a href="{% url 'blogs:detail' blog_id=blog.id %}">Read Article</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </body>

</html>

app_blog/blogs/templates/blogs/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New</title>
</head>
<body>
<h1 style="text-align: center;">Add Article</h1>
<div style="width: 70%; margin: 0px auto;">
    <div>
        <div style="margin: 60px 20px;">
            <form action="{% url 'blogs:new' %}" method="POST">{% csrf_token %}
                {{ form.as_p}}
                <button type="submit" class="btn">Save</button>
            </form>
        </div>
        <div style="text-align: center; margin-top: 50px;">
       <a href=" {% url 'blogs:index' %}">Return Top</a> 
        </div>
    </div>
</div>
    
</body>
</html>